## Task

In this task you will clean the country column and parse the date column in the **store_income_data_task.csv** file.

In [3]:
# Load up store_income_data.csv
# Load the dataset and display the first five observations
import pandas as pd

df = pd.read_csv('store_income_data_task.csv')
df.head()

,id,store_name,store_email,department,income,date_measured,country
0,1,"Cullen/Frost Bankers, Inc.",NaN,Clothing,$54438554.24,4-2-2006,United States/
1,2,Nordson Corporation,NaN,Tools,$41744177.01,4-1-2006,Britain
2,3,"Stag Industrial, Inc.",NaN,Beauty,$36152340.34,12-9-2003,United States
3,4,FIRST REPUBLIC BANK,ecanadine3@fc2.com,Automotive,$8928350.04,8-5-2006,Britain/
4,5,Mercantile Bank Corporation,NaN,Baby,$33552742.32,21-1-1973,United Kingdom

1. Take a look at all the unique values in the "country" column. Then, convert the column to lowercase and remove any trailing white spaces.

In [21]:
# View unique country values, then clean formatting (lowercase + strip spaces)
# Clean country column (lowercase, strip spaces, remove punctuation)
import pandas as pd
import numpy as np
from datetime import date

df = pd.read_csv("store_income_data_task.csv")
df.head(5)

,id,store_name,store_email,department,income,date_measured,country
0,1,"Cullen/Frost Bankers, Inc.",NaN,Clothing,$54438554.24,4-2-2006,United States/
1,2,Nordson Corporation,NaN,Tools,$41744177.01,4-1-2006,Britain
2,3,"Stag Industrial, Inc.",NaN,Beauty,$36152340.34,12-9-2003,United States
3,4,FIRST REPUBLIC BANK,ecanadine3@fc2.com,Automotive,$8928350.04,8-5-2006,Britain/
4,5,Mercantile Bank Corporation,NaN,Baby,$33552742.32,21-1-1973,United Kingdom

In [22]:
df["country"].unique()

<StringArray>
[           'United States/',                   'Britain',
            ' United States',                  'Britain/',
           ' United Kingdom',                      'U.K.',
                       'SA ',                      'U.K/',
                   'America',            'United Kingdom',
                         nan,             'united states',
                     ' S.A.',                  'England ',
                        'UK',                     'S.A./',
                   'ENGLAND',                   'BRITAIN',
                       'U.K',                      'U.K ',
                  'America/',                       'SA.',
                     'S.A. ',                       'u.k',
                        'uk',                         ' ',
                       'UK.',                  'England/',
                   'england',                  ' Britain',
  'united states of america',                       'UK/',
                       'SA/',                        'SA',
                  'England.',            'UNITED KINGDOM',
                  'America.',                     'S.A..',
                      's.a.',                      ' U.K',
 ' United States of America',                  'Britain ',
                   'England',                       ' SA',
 'United States of America.', 'United States of America/',
            'United States.',     's. africasouth africa',
                  ' England',           'United Kingdom ',
 'United States of America ',                       ' UK',
            'united kingdom',                   'AMERICA',
                  'America ',  'UNITED STATES OF AMERICA',
    ' S. AfricaSouth Africa',                   'america',
     'S. AFRICASOUTH AFRICA',                  'Britain.',
                         '/',           'United Kingdom.',
             'United States',                  ' America',
             'UNITED STATES',                        'sa',
  'United States of America',                       'UK ',
            'United States ',    'S. AfricaSouth Africa/',
                      'S.A.',           'United Kingdom/',
    'S. AfricaSouth Africa ',    'S. AfricaSouth Africa.',
     'S. AfricaSouth Africa',                         '.',
                   'britain']
Length: 77, dtype: str

In [23]:
df["country"] = df["country"].str.strip().str.lower()
df["country"].unique()

<StringArray>
[           'united states/',                   'britain',
             'united states',                  'britain/',
            'united kingdom',                      'u.k.',
                        'sa',                      'u.k/',
                   'america',                         nan,
                      's.a.',                   'england',
                        'uk',                     's.a./',
                       'u.k',                  'america/',
                       'sa.',                          '',
                       'uk.',                  'england/',
  'united states of america',                       'uk/',
                       'sa/',                  'england.',
                  'america.',                     's.a..',
 'united states of america.', 'united states of america/',
            'united states.',     's. africasouth africa',
                  'britain.',                         '/',
           'united kingdom.',    's. africasouth africa/',
           'united kingdom/',    's. africasouth africa.',
                         '.']
Length: 37, dtype: str

2. Note that there should only be three separate countries. Eliminate all variations, so that 'South Africa', 'United Kingdom' and 'United States' are the only three countries.

In [27]:
def clean_country(country):
    if pd.isna(country):
        return np.nan

    country = str(country).lower().strip().replace("/", "")

    if country in ["south africa", "sa", "s.a"]:
        return "South Africa"

    elif country in ["united kingdom", "uk", "u.k", "britain", "u.k."]:
        return "United Kingdom"

    elif country in ["united states", "us", "u.s", "usa"]:
        return "United States"

    return np.nan

In [28]:
df["country"] = df["country"].apply(clean_country)
df["country"].unique()

<StringArray>
['United States', 'United Kingdom', 'South Africa', nan]
Length: 4, dtype: str

3. Create a new column called `days_ago` in the DataFrame that is a copy of the 'date_measured' column but instead it is a number that shows how many days ago it was measured from the current date. Note that the current date can be obtained using `datetime.date.today()`.

In [29]:
df["date_measured"] = pd.to_datetime(df["date_measured"], dayfirst=True)

today = pd.to_datetime(date.today())

df["days_ago"] = (today - df["date_measured"]).dt.days

df[["date_measured", "days_ago"]].head()

  date_measured  days_ago
0    2006-02-04      7382
1    2006-01-04      7413
2    2003-09-12      8258
3    2006-05-08      7289
4    1973-01-21     19449